# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNjbQRdimv0gyWkGWuaS61UlxVOTdKPJ
"""

import streamlit as st
from backend import generate_response   # your function that returns the optimized prompt

st.set_page_config(page_title="Prompt Optimizer")

st.title("Prompt Optimizer")

# Store current output so it persists between reruns
if "optimized_text" not in st.session_state:
    st.session_state.optimized_text = ""

# PROMPT INPUT
user_prompt = st.text_area("Enter your prompt:")

# RUN BUTTON
if st.button("Optimize") and user_prompt.strip():
    with st.spinner("Working…"):
        st.session_state.optimized_text = generate_response(user_prompt)

# OUTPUT BOX
st.text_area(
    "Optimized prompt:",
    value=st.session_state.optimized_text,
    height=200,
    key="output_box",
)